### ISSUE TITLE
Axios timeout default value is 1 sec

### ISSUE THREAD

**Issue by boly38** [jakobbouchard/umami-api-client#3]
Following #1 fix, I now have the root cause of the action report flaky failure.

Here is an example:
```` 
Run boly38/action-umami-report@main
ERROR: Error: Could not get websites
Options: {}
Stacktrace:Error: Login failed
Options: {"server":"umami.example.fr","username":"***"}
Stacktrace:AxiosError: timeout of 1000ms exceeded


Error: Error: Could not get websites
Options: {}
Stacktrace:Error: Login failed
Options: {"server":"umami.example.fr","username":"***"}
Stacktrace:AxiosError: timeout of 1000ms exceeded
```` 

The default timeout set with axios library is only 1 sec. [source coce](https://github.com/jakobbouchard/umami-api-client/blob/main/src/UmamiAPIClient.ts#L404)

When the server takes some time to wake up this could be insuficent. 

# expected
As umami-api-client user, I would like some setup options (either `UmamiAPIClient` constructor additional arg, else new setter) : example `fetchTimeoutMs`

**Comment by boly38** [comment]
@jakobbouchard please 🙏 create a `0.5.2` release ;)

**Comment by imjuniper** [comment]
@boly38 it's released! :)

**Comment by boly38** [comment]
oO ok it's just that [github tag](https://github.com/jakobbouchard/umami-api-client/tags) is not pushed 🙏 thX

**Comment by imjuniper** [comment]
oh oops, forgot to push the tags. i'll do that a bit later
