### ISSUE TITLE
period?: TimePeriod：Add option for "All Time" or custom start date in TimePeriod selection

### ISSUE THREAD

**Issue by ihavenoideaa** [jakobbouchard/umami-api-client#44]
Currently, the TimePeriod selection in the author's period only allows a maximum duration of one month. It would be useful to have an option for "All Time" so that users can view the data for the entire available period. Alternatively, it would be great to be able to input a specific start date using Date.now() as the current time and subtracting the date the user inputs. This would provide more flexibility in analyzing the data over longer or customized periods.

Could you please consider adding these features to improve the usability of the author's period selection? Thank you!

**Comment by ihavenoideaa** [comment]
Or simply add a period like -99 years to show all the time data

**Comment by imjuniper** [comment]
Hello! :wave: I no longer work in web development, and do not have a lot of free time or interest in maintaining this package anymore. I am closing all issues and PR for it and will archive the repository, but if anybody is interested in maintaining it, I am willing to transfer the repository and NPM package.
