### ISSUE TITLE
Industrialization : activate houndci

### ISSUE THREAD

**Issue by boly38** [jakobbouchard/umami-api-client#6]
try to add houndci to this repository to decorate future PR with syntax issues.

To do:
- create an exemple of houndci config: [.hound.yml](https://github.com/boly38/node-mongotools/blob/main/.hound.yml) at the repo root directory
- go to https://houndci.com/ , sign in, then activate houndci for `jakobbouchard/umami-api-client` repository

**Comment by imjuniper** [comment]
I'll be looking into it soon! Currently have a lot of uni projects to do :)

**Comment by imjuniper** [comment]
I added it :) I also converted the project to vitest, added eslint, prettier and husky!
I converted the project to pnpm too, for faster installs
