### ISSUE TITLE
Incompatible with umami version 1.39.0 and above

### ISSUE THREAD

**Issue by rohandebsarkar** [jakobbouchard/umami-api-client#9]
This client is incompatible with umami versions 1.39.0 and above.

v1.39.0 introduced UUID based queries, replacing the previous integer based queries for security reasons.

I noticed this was not working while using [umami-action-report](https://github.com/boly38/action-umami-report). Since it uses this client to interact with umami API, I have opened the issue here.

**Comment by imjuniper** [comment]
thanks for the report! I'll be fixing it by the end of the weekend, maybe tomorrow :)

**Comment by boly38** [comment]
💡 Note for action report but that could be nice for umami-api-client too: we could append a new [tag](https://github.com/jakobbouchard/umami-api-client/tags) (in addition to existing) that match tested umami backend version.  A way to retrieve versions compatibility matrix.

For example, current api [0.5.2](https://github.com/jakobbouchard/umami-api-client/releases/tag/v0.5.2)+umamit-action-report [v2.2](https://github.com/boly38/action-umami-report/releases/tag/v2.2) works well with [umami server `1.38.0`](https://github.com/umami-software/umami/releases/tag/v1.38.0) so add a tag `umami-server-1.38.0` ([example](https://github.com/boly38/action-umami-report/releases/tag/umami-server-1.38.0)).
and same for future versions..

**Comment by imjuniper** [comment]
Hey, currently working on this. It seems that the id is still a thing, but all of the object parameters changed names, so basically every parameter in the app will need to change name, so that's fun. They all went from `snake_case` to `camelCase`...

**Comment by imjuniper** [comment]
The latest release moved to the new API, some code changes will be needed though :)
